In [1]:
import numpy as np
import torch

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [6]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [8]:
print('t[0] t[1] t[-1] = \t', t[0], t[1], t[-1] )
print('t[2:5] t[4:-1] = \t' , t[2:5], t[4:-1])
print('t[:2] t[3:] \t', t[:2] , t[3:])

t[0] t[1] t[-1] = 	 0.0 1.0 6.0
t[2:5] t[4:-1] = 	 [2. 3. 4.] [4. 5.]
t[:2] t[3:] 	 [0. 1.] [3. 4. 5. 6.]


In [9]:
t = np.array([[1.,2.,3.,], [4.,5.,6.], [7.,8.,9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [10]:
print('Rank of t : ' , t.ndim)
print("shape of t : ", t.shape) 

Rank of t :  2
shape of t :  (4, 3)


### 이제는 파이토치로.

In [11]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [14]:
t = torch.Tensor([0, 1, 2, 3, 4, 5, 6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [15]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0] , t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [16]:
t = torch.FloatTensor([[1.,2.,3.,], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [18]:
print(t.dim())
print(t.size())
print(t.shape)
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

#### 브로드 캐스팅
- 덧셈과 뺄셈을 할 때는 행렬의 크기가 같아야 하며
- 곱셈시에는 행렬의 내접하는 부분의 크기가 같아야 한다. 

In [19]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [20]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 원래는 연산 불가능하지만 [3,3] 으로 바꿔줌.

print(m1+m2)

tensor([[4., 5.]])


In [25]:
# 2 * 1 vector + 1 * 2 vector 

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])

print(m1 + m2)

# [1,2] ->    [1,2] [1,2]
# [3], [4] -> [3,4] [3,4]

tensor([[4., 5.],
        [5., 6.]])


In [26]:
# 2 * 1 vector + 1 * 2 vector 
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])

print(m1 + m2)

# [1,2]
# [3], [4]

tensor([[4., 5.],
        [5., 6.]])


#### 브로드 캐스팅은 자동으로 수행되기 때문에 사용자는 에러를 확인하지 못할 수 있다.

In [31]:
print()
print("-------------")
print("Mul  vs  MatMul")
print("-------------")

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])

print("shape of Matrix 1 :" , m1.shape)
print("shape of Matrix 2 :" , m2.shape)
print(m1.matmul(m2)) #원래 행렬의 곲의 값. 

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]]) # 여기서 브로드 캐스팅이 발생.
print(m1*m2)
print(m1.mul(m2))



-------------
Mul  vs  MatMul
-------------
shape of Matrix 1 : torch.Size([2, 2])
shape of Matrix 2 : torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [32]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [37]:
#long Tensor에 대해서는 오류 출력
t = torch.LongTensor([1,2])
print(t)
try:
  print(t.mean())
except Exception as exc:
  print(exc)


tensor([1, 2])
mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [35]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [36]:
print(t.mean())
print(t.mean(dim=0)) # -> 열로 묶음  [? , ?]
print(t.mean(dim=1)) # -> 행으로 묶음. [[?] [?]]
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [38]:
t = torch.Tensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [39]:
print(t.sum())
print(t.sum(dim=0)) #첫번째 dim에 대해 (열)
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [40]:
t = torch.Tensor([[1,2], [3,4]])
print(t)


tensor([[1., 2.],
        [3., 4.]])


In [41]:
print(t.max()) #차원이 없어짐.

tensor(4.)


In [42]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [45]:
print("Max : ", t.max(dim=0)[0])
print("Argument : ", t.max(dim=0)[1])

#Argument 즉 값과 Index까지 한번에 return 해주는 것을 알 수 있다.

Max :  tensor([3., 4.])
Argument :  tensor([1, 1])


In [46]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
