<a href="https://colab.research.google.com/github/younghoonNa/PyTorch/blob/main/Pytorch/Pytorch_%EA%B8%B0%EB%B3%B8%EC%97%B0%EC%82%B02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

## View (numpy에서 reshape)

In [3]:
t = np.array([[[0,1,2] , 
               [3,4,5]] ,
              
              [[6,7,8],
              [9,10,11]]])

ft = torch.Tensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [4]:
# view -> np에서 reshape() 와 같음.
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [5]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

In [7]:
ft = torch.Tensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [8]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [9]:
# squeeze(dim = ? ) -> 해당 dim에 해당하는 열이 0 일경우 삭제를 진행함. if dim=3 인 경우 삭제 안하구 그냥 넘어감.

## Unsqueeze

In [10]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [17]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

#unsqueeze(0) 일 경우 0번 째 인덱스인 행에 대하여  //  dim = 0 과 같음 , squeeze(1)은 dim(1) 과 같다.
print("=================")
#unsqueeze(1) 일 경우 1번 째 인덱스인 열에 대하여 차원 증가.

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [19]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [20]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [22]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)
# dim = -1 일 경우 -> 마지막 dimension에 대해서

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [23]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [24]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [25]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [27]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [28]:
x = torch.Tensor([[1,2], [3,4]])
y = torch.Tensor([[5,6], [7,8]])

In [30]:
print(torch.cat([x,y], dim=0)) # dim = 0일 경우 행으로 늘림 밑으로 = 이렇게 
print(torch.cat([x,y], dim=1)) # dim = 1일 경우 열으로 늘림.  ||| 이렇게

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking -> Concatenate를 더 편리하게

In [31]:
x = torch.Tensor([1,4])
y = torch.Tensor([2,5])
z = torch.Tensor([3,6])

In [32]:
print(torch.stack([x,y,z])) #default는 dim = 0 즉 밑으로 쌓음
print(torch.stack([x,y,z], dim = 1)) #dim = 1 선언하게 되면 옆으로 쌓음.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [33]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [38]:
print(torch.cat([x,y,z]))

tensor([1., 4., 2., 5., 3., 6.])


## Ones and Zeros

In [40]:
x = torch.Tensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [41]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

# device에도 똑같이 적용. 
#즉 cpu에서 텐서를 만들고 gpu의 텐서와 병합을 할 때 오류가 발생하는데
# ones/zeros를 사용할 경우 같은 device에 선언해줌.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Inplace Operation
- mul_ , add_ 등 과 같이 `_`  을 붙일 경우 대체 가능.
- but Pytorch의 Garbage Collector가 매우 잘 구현되어 있어 성능상의 차이는 별로 없다고 함.

In [44]:
x = torch.Tensor([[1,2], [3,4]])
print("x * 2")
print(x.mul(2.))
print("X is ?? : ")
print(x)
print("x * 2")
print(x.mul_(2.))
print("x is changed")
print(x)

x * 2
tensor([[2., 4.],
        [6., 8.]])
X is ?? : 
tensor([[1., 2.],
        [3., 4.]])
x * 2
tensor([[2., 4.],
        [6., 8.]])
x is changed
tensor([[2., 4.],
        [6., 8.]])
